// @generated FILE — do not edit
// Generated by: scripts/generate-types.ts

import raw from './data/cache-number.json' assert { type: 'json' };

/**
 * Schema for the cache-number.json produced by CacheNumberTool
 */
export interface CacheNumber {
  /**
   * Numeric cache id of the most recent ID
   */
  cacheID: number;
}

const data = raw as unknown as CacheNumber;
export default data;
