// @generated FILE — do not edit
// Generated by: scripts/generate-types.ts

import raw from './data/npcs.g.json' assert { type: 'json' };

/**
 * Schema for NPCs exported data
 */
export type NPCs = {
  id: number;
  name: string;
  examine?: string | null;
  size?: number | null;
  combatLevel?: number | null;
  attackSpeed?: number | null;
  aggressive?: boolean | null;
  poisonous?: boolean | null;
  immuneToPoison?: boolean | null;
  immuneToVenom?: boolean | null;
  options?: (string | null)[] | null;
  hitpoints?: number | null;
  attributes?: {
    [k: string]: any;
  } | null;
  animations?: {
    [k: string]: any;
  } | null;
  params?: {
    [k: string]: any;
  } | null;
  [k: string]: any;
}[];

const data = raw as unknown as NPCs;
export default data;
