// @generated FILE — do not edit
// Generated by: scripts/generate-types.ts

import raw from './data/quests.g.json' assert { type: 'json' };

/**
 * A schema for quests parsed from RuneLite's Quest enum.
 */
export type Quests = {
  /**
   * RuneLite quest ID used by script engine
   */
  id: number;
  /**
   * Enum constant name in RuneLite's Quest.java
   */
  enum: string;
  /**
   * Display name of the quest
   */
  name: string;
}[];

const data = raw as unknown as Quests;
export default data;
