// @generated FILE — do not edit
// Generated by: scripts/generate-types.ts

import raw from './data/skills.g.json' assert { type: 'json' };

/**
 * A schema for the generated Skills.json file: an array of skill names.
 */
export type Skills = (
  | 'Attack'
  | 'Cooking'
  | 'Crafting'
  | 'Defence'
  | 'Firemaking'
  | 'Fishing'
  | 'Hitpoints'
  | 'Magic'
  | 'Mining'
  | 'Prayer'
  | 'Ranged'
  | 'Runecrafting'
  | 'Smithing'
  | 'Strength'
  | 'Woodcutting'
  | 'Agility'
  | 'Construction'
  | 'Farming'
  | 'Fletching'
  | 'Herblore'
  | 'Hunter'
  | 'Slayer'
  | 'Thieving'
)[];

const data = raw as unknown as Skills;
export default data;
