// @generated FILE — do not edit
// Generated by: scripts/generate-types.ts

import raw from './data/slotStats.g.json' assert { type: 'json' };

/**
 * Schema for slot stats data extracted from OSRS items
 */
export type SlotStats = {
  /**
   * The item's ID
   */
  id: number | null;
  /**
   * The item's name
   */
  name: string;
  /**
   * Whether the item is members-only
   */
  members: boolean;
  /**
   * Stab attack bonus
   */
  stabAttack: number;
  /**
   * Slash attack bonus
   */
  slashAttack: number;
  /**
   * Crush attack bonus
   */
  crushAttack: number;
  /**
   * Magic attack bonus
   */
  magicAttack: number;
  /**
   * Ranged attack bonus
   */
  rangedAttack: number;
  /**
   * Stab defence bonus
   */
  stabDefence: number;
  /**
   * Slash defence bonus
   */
  slashDefence: number;
  /**
   * Crush defence bonus
   */
  crushDefence: number;
  /**
   * Magic defence bonus
   */
  magicDefence: number;
  /**
   * Ranged defence bonus
   */
  rangedDefence: number;
  /**
   * Strength bonus
   */
  strengthBonus: number;
  /**
   * Ranged strength bonus
   */
  rangedStrength: number;
  /**
   * Magic damage bonus
   */
  magicDamage: number;
  /**
   * Prayer bonus
   */
  prayerBonus: number;
  /**
   * Item weight in kg
   */
  weight: number;
  /**
   * Attack speed (for weapons)
   */
  speed?: number | null;
  /**
   * Equipment slot
   */
  slot:
    | 'Ammunition'
    | 'Body'
    | 'Cape'
    | 'Feet'
    | 'Hands'
    | 'Head'
    | 'Legs'
    | 'Neck'
    | 'Ring'
    | 'Shield'
    | 'Weapon'
    | 'Two-handed';
}[];

const data = raw as unknown as SlotStats;
export default data;
