name: Extract JSON

on:
  workflow_dispatch:
  schedule:
    - cron: "15 15 * * 4" # Every Thursday at 1515 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout runelite
        uses: actions/checkout@v4
        with:
          repository: runelite/runelite
          path: runelite

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Install npm dependencies
        run: |
          npm install

      - name: Get the cache
        run: |
          npm run getNewestCache

      - name: Patch Runelite
        run: |
          cd runelite/cache/src/main/java/net/runelite/cache
          curl -o CollisionMapDumper.java https://raw.githubusercontent.com/Skretzo/runelite/refs/heads/shortest-path-collision-map-dumper/cache/src/main/java/net/runelite/cache/CollisionMapDumper.java

      # replace the following in the key file
      # Replace the words "mapsquares" with "regions" and "key" with "keys" in the keys.json file
      - name: Patch the key file
        run: |
          sed -i 's/mapsquares/regions/g' keys.json
          sed -i 's/key/keys/g' keys.json

      - name: Patch Runelite with pom file
        run: |
          cp pom.patch runelite/cache
          cd runelite/cache
          git apply pom.patch

      - name: Build Runelite with Maven
        run: |
          cd runelite/cache
          mvn -B package --file pom.xml -DskipTests

      - name: Copy jar file to the root directory
        run: |
          find runelite/cache/target -name "*-jar-with-dependencies.jar" -exec cp {} ./cache.jar \;

      - name: Export collision map
        run: |
          mkdir -p data
          java -jar cache.jar -c ./cache --xteapath ./keys.json --outputdir "output"

      - name: Clean before commit
        run: |
          rm -fr runelite
          rm cache.jar

      # - name: Commit changes
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     default_author: github_actions
      #     message: Extracted json from the cache file
