name: Extract JSON

on:
  workflow_dispatch:
  schedule:
    - cron: "15 15 * * 4" # Every Thursday at 1515 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install npm dependencies
        run: scripts/installDependencies.sh

      - name: Build Runelite and download cache
        run: scripts/buildRuneliteAndDownloadCache.sh

      - name: Download cache.jar
        run: scripts/downloadCacheJar.sh

      - name: Export items
        run: tools/item/exportItems.sh

      - name: Export npcs
        run: tools/npc/exportNpcs.sh

      - name: Export objects
        run: tools/objects/exportObjects.sh

      - name: Clean before commit
        run: scripts/cleanBeforeCommit.sh

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: Extracted json from the cache file
