name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

  
    steps:
    # checkout the local repo
    - name: Checkout repository
      uses: actions/checkout@v2
    

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: runelite/runelite
        path: runelite

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: |
        cd runelite/cache
        mvn -B package --file pom.xml
