name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: runelite/runelite
        path: runelite

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install npm dependencies
      run: |
        npm install

    - name: Get the cache
      run: |
        npm run getNewest

    - name: Build with Maven
      run: |
        cd runelite/cache
        mvn -B package --file pom.xml -DskipTests

    - name: Copy jar file to the root directory
      run: |
        find runelite/cache/target -name "*-jar-with-dependencies.jar" -exec cp {} ./cache.jar \;

    - name: Upload cache.jar
      uses: actions/upload-artifact@v4
      with:
        name: cache.jar
        path: cache.jar

    - name: Run the jar file
      run: |
        java -jar -cp cache.jar net.runelite.cache.Cache -cache ./cache
