name: Build Runelite

on:
  workflow_call:
    outputs:
      cache-jar-path:
        description: "Path to the built cache.jar"
        value: ${{ jobs.build.outputs.cache-jar-path }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      cache-jar-path: ${{ steps.set-output.outputs.cache-jar-path }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout runelite
        uses: actions/checkout@v4
        with:
          repository: runelite/runelite
          path: runelite

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install npm dependencies
        run: npm install

      - name: Get the cache
        run: npm run getNewestCache

      - name: Patch Runelite with pom file
        run: |
          cp pom.patch runelite/cache
          cd runelite/cache
          git apply pom.patch

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Build Runelite with Maven
        run: |
          cd runelite/cache
          mvn -B package --file pom.xml -DskipTests

      - name: Copy jar file to the root directory
        run: |
          find runelite/cache/target -name "*-jar-with-dependencies.jar" -exec cp {} ./cache.jar \;

      - name: Upload cache.jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: cache-jar
          path: ./cache.jar

      - name: Set output for cache-jar-path
        id: set-output
        run: echo "cache-jar-path=cache.jar" >> $GITHUB_OUTPUT